### ISSUE TITLE
Uncaught ReferenceErrors

### ISSUE THREAD

**Issue by mbiesiad** [scrapy/scrapy.org#224]
Hi,

# Description
`Uncaught ReferenceError: _refersion is not defined` and `Uncaught ReferenceError: analytics is not defined` occurs.

# Steps to replicate
1. Go to: https://scrapy.org/
2. Check DevTools Console
3. Go to: https://docs.scrapy.org/en/latest/faq.html
4. Check DevTools Console

# Additional information
Operating system: Windows
Browser: Chromium based and Firefox

Screenshots:
![image](https://user-images.githubusercontent.com/18367606/193450547-c528c1c6-9bb1-4979-8be5-7846c414d146.png)

![image](https://user-images.githubusercontent.com/18367606/193450536-8e656f26-48b1-430b-aebd-6bff09613f5b.png)

Best wishes,

**Comment by Ishika414** [comment]
I would like to work on this issue.

**Comment by Laerte** [comment]
@Gallaecio Just tested going to https://scrapy.org/, this error happens because i'm using Ad blocking extension, when i disable for the page the error don't happen since the tracking script is loaded, we could or insert this inside a `try { ... } catch` block to not display error or leave like it is and close this issue (since the one from docs is now fixed).

**Comment by mbiesiad** [comment]
Hi, thank you for messages here. Yup, the best IMO will be to use `try { ... } catch` block, but final decision/approach is for you of course. Best wishes,

**Comment by Gallaecio** [comment]
A try-catch that prevents the error when using ad blockers sounds good to me.
