### ISSUE TITLE
Add Requests to code sample in home page

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapy.org#30]
The code in scrapy.org is all nice and simple but I think we should add some code to follow requests, otherwise we're only showing the scraping (data extraction) side of Scrapy and leaving out the (arguably more important) crawling part.

What do you think @eliasdorneles @kmike @dangra @curita?

**Comment by kmike** [comment]
+1 to update https://github.com/scrapy/scrapy.github.io/pull/28 with @pablohoffman's suggestion.

**Comment by eliasdorneles** [comment]
+1 I like it.
I'll try to come up with something short.

**Comment by pablohoffman** [comment]
thanks @eliasdorneles

**Comment by eliasdorneles** [comment]
I'll make some proposals here, and I'll make a PR when we agree on it (because I need to manually format the code).

So, this is a spider that goes through the blog archives and extracts the titles.

Here is option A, demonstrating LinkExtractor:

```
import scrapy
from scrapy.linkextractors import LinkExtractor

class BlogSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = ['http://blog.scrapinghub.com']

    def parse(self, response):
        for link in LinkExtractor(allow=r'/\d\d\d\d/\d\d/$').extract_links(response):
            yield scrapy.Request(response.urljoin(link.url), self.parse_titles)

    def parse_titles(self, response):
        for post_title in response.css('div.entries > ul > li a::text').extract():
            yield {'title': post_title}
```

Relatively straightforward to understand, but a bit verbose.


Here is option B, same thing but without LinkExtractor, using `re()` method:

```
import scrapy

class BlogSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = ['http://blog.scrapinghub.com']

    def parse(self, response):
        for url in response.css('ul li a::attr("href")').re(r'.*/\d\d\d\d/\d\d/$'):
            yield scrapy.Request(response.urljoin(url), self.parse_titles)

    def parse_titles(self, response):
        for post_title in response.css('div.entries > ul > li a::text').extract():
            yield {'title': post_title}
```

The `re()` method may be not that clear at first sight, but I guess people that know regexp will probably recognize what it does.

I have showed around some other options, but option B hits the spot for me.

What do you think?

**Comment by kmike** [comment]
I like a variant with `.re` more, because it seems that our LinkExtractor API can be improved. The example with link extractors should have looked similar to

```
 for link in scrapy.iter_links(response, allow=r'/\d{4}\d{2}/'):
```

or maybe

```
for link in response.css("div.foo").links(allow='/\d{4}\d{2}/'):
```

or
 
```
container = response.css("div.foo")
for link in scrapy.iter_links(container, allow='/\d{4}\d{2}/'):
```

or even a more low-level
```
for url in response.xpath("//a/@href").extract():
    if re.match(url, r'/\d{4}\d{2}/'):
        yield scrapy.Request(response.urljoin(url), self.parse_titles) 
```

so I'm not sure showing LinkExtractor is good here. It has some nice features - link.url doesn't need response.urljoin, there are other filtering options, and it does its own deduplication, but the API requires user to write unnecessary code; LinkExtractor is an opaque "all-in-one" utility, and it requires an extra import.

**Comment by eliasdorneles** [comment]
@kmike: oops, thanks for the reminder, I removed the unneeded response.urljoin from the LinkExtractor example =)

**Comment by eliasdorneles** [comment]
And I agree with everything you said, and I specially liked the `response.css("div.foo").links(allow='/\d{4}\d{2}/')` API suggestion. =)

**Comment by dangra** [comment]
I learn to like `Selector.links()` method too, it has been discussed in the past in scrapy/scrapy#331  and scrapy/scrapy#548. Happens that now with unified selectors and a single linkextractor reference implementation we are much closer to integrate link extraction to Selectors.

It can be a planned feature for Scrapy 1.1, for 1.0 I prefer the `.re()` example (no LinkExtractor)

**Comment by Curita** [comment]
I like `.links()` too, I think there's enough consensus to announce it as the final solution in scrapy/scrapy#548 and add it to 1.1.

+1 to use `.re()` until that's implemented.

**Comment by eliasdorneles** [comment]
Alrighty, I'll make a PR to scrapy.org repo with the snippet using `.re()`. :+1:

**Comment by eliasdorneles** [comment]
Here it is: https://github.com/scrapy/scrapy.org/pull/31

**Comment by redapple** [comment]
@eliasdorneles , I guess this issue can be closed now.

**Comment by eliasdorneles** [comment]
+1, I don't have access to close it though.
@pablohoffman feeling like closing issues? :)

**Comment by redapple** [comment]
@eliasdorneles , done.
