### ISSUE TITLE
Add resources section

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy.org#63]
Transfer https://github.com/scrapy/scrapy/wiki links to articles, blog posts, videos and talks to a new section on scrapy.org website.

Also, add a few important ones in the scrapy docs too.

**Comment by jagadeeshv16** [comment]
@redapple, can you detail me on this task.

**Comment by redapple** [comment]
hello @jagadeeshv16 , the idea here is to review blog posts and articles (old and new, many links are https://github.com/scrapy/scrapy/wiki) and select the most relevant ones (in terms of quality, use of newer idioms, best practices) and compile them into a page to this repository.
Also, a couple of books on Scrapy have been published in recent months, these could be referenced too.
Does that make sense?

**Comment by jagadeeshv16** [comment]
Hi @redapple,

I will add a new section called resources under menu and start importing these links directly for following sections:

1. Getting started
2. Google Summer of Code
3. Books (you're right! no new books since then)
4. Slides
5. Projects, tools and libraries using Scrapy
6. Developer documentation
7. Scrapy Enhancement Proposals

Regarding Following Sections:

1. Videos
2. Articles & blog posts

I can also go through the pull requests for latest blog posts and add them if appropriate or has new content, and regarding videos i will look into vimeo or youtube to see if any new videos are available.

Let me know, if you have any suggestions or any changes to what i mentioned above. i will start with the new page.

**Comment by redapple** [comment]
FTR, I started https://github.com/scrapy/scrapy.org/issues/63
